apiVersion: v1
kind: Service
metadata:
  name: gabriella-backend
  namespace: grupp5
  labels:
    app: gabriella-backend
spec:
  selector:
    app: gabriella-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
